name: Python CI/CD

on:
  push:
    branches: 
      - test
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pytest

  create-pull-request:
    name: Create Pull Request
    needs: lint-and-test
    if: github.ref == 'refs/heads/test' && needs.lint-and-test.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            try {
                const { data: openPRs } = await github.rest.pulls.list({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    head: 'test',
                    base: 'main',
                    state: 'open'
                });

                if (openPRs.length > 0) {
                    console.log('A pull request already exists. Skipping creation.');
                    return;
                }

                const { data: pull } = await github.rest.pulls.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: 'Automated Pull Request from Test Branch',
                    head: 'test',
                    base: 'main',
                    body: 'This pull request was automatically created after successful linting and testing.',
                });

                console.log(`Created pull request: ${pull.html_url}`);
            } catch (error) {
                console.error('Error creating pull request:', error);
            }