name: GHAction WF - Dependent Jobs
run-name: GH-WF-Depedent Jobs

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is a test  job on Ubuntu-Latest"
  
  lint:
    runs-on: windows-latest
    steps:
      - run: echo "This is a lint job on windows-Latest"
  
  release:
    runs-on: macos-latest
    steps:
      - run: echo "This is a release job MacOS-Latest"