name: GHActions Label Demo
run-name: Workflow on Labels - ${{ github.actor }}
on:
  label:
    types: [created, edited, deleted]
jobs:
  GHActions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running GH Action when a label was either created, edited or delete."